[project]
name = "subjective_binance_last_minute_symbol_stream_datasource"
version = "0.1.0"
description = "Subjective data source plugin: Binance Last Minute Symbol Stream."
requires-python = ">=3.12"
dependencies = [
  "certifi",
  "binance-connector>=3.12.0",
  "brainboost-rclone-oauth-package @ git+https://github.com/Subjective-Technologies/brainboost_rclone_oauth_package.git",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

